# Enable/Disable blank issues (if false, users must use a template)
blank_issues_enabled: false

# Links to appear on new issue page
contact_links:
  - name: "Community Discussions"
    url: "https://join.slack.com/t/xsky-ai/shared_invite/zt-2xhvkudv9-nHvD1g8Smp227sM51x_Meg"
    about: "Please ask and answer questions here."
  - name: "Documentation"
    url: "https://xsky.fellou.ai/docs/"
    about: "Find answers and guides in our official documentation."

# Issue templates configuration
